import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { muli } from "./_fonts";
import { Footer, Header } from "./_components";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={muli.className}>
        <Header />
        <div className={"max-w-screen-2xl mx-auto "}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
